services:
  redis:
    image: redis:latest
  celery: 
    image: fpgaemuweb
    working_dir: /home/fpgaemuweb
    entrypoint: ['/bin/bash','-c']
    command: ["celery -A appp.celery worker --concurrency=5"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - fpgaemuwork:/home/fpgaemuweb/work
  web:
    build: .
    image: fpgaemuweb
    ports:
      - "80:80"
    volumes:
      - fpgaemuwork:/home/fpgaemuweb/work
volumes:
  fpgaemuwork: {}
