version: "3.3"  # optional since v1.27.0
services:
  redis:
    restart: always
    image: redis:alpine
    networks:
      - tunnelnetwork
  celery: 
    restart: always
    image: fpgaemuopi
    working_dir: /home/fpgaemuweb
    entrypoint: ['/bin/bash','-c']
    command: ["uv run celery -A appp.celery worker --concurrency=5"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./work:/home/fpgaemuweb/work
    networks:
      - tunnelnetwork
  web:
    # Warning!: fpgaemubase image must have been built in advance.
    restart: always
    image: fpgaemuopi
    build:
      context: .
      dockerfile: DockerfileOpiServer
    ports:
      - "8000:80"
    volumes:
      - ./work:/home/fpgaemuweb/work
    networks:
      - tunnelnetwork

networks:
  tunnelnetwork:
    external: true
